package net.kyrptonaught.ToolBox;

import com.google.gson.JsonObject;
import net.kyrptonaught.ToolBox.IO.ConfigLoader;
import net.kyrptonaught.ToolBox.IO.FileHelper;
import net.kyrptonaught.ToolBox.IO.GithubHelper;
import net.kyrptonaught.ToolBox.configs.BranchConfig;

import java.io.InputStream;
import java.nio.file.Path;

public class AutoHash {

    public static void autoHash() {
        String toolboxJson = FileHelper.readFile(Path.of("toolbox.json"));
        BranchConfig config = ConfigLoader.parseToolboxConfig(toolboxJson);

        autoHash(config);

        FileHelper.writeFile(Path.of("toolbox.json"), ConfigLoader.serializeToolboxInstall(config));
    }

    public static void autoHash(BranchConfig config) {
        for (BranchConfig.Dependency dependency : config.dependencies) {
            if (dependency.type == BranchConfig.TYPE.GIT) {
                String apiCall = GithubHelper.convertRepoToApiCall(dependency.url);
                JsonObject response = FileHelper.download(apiCall, JsonObject.class);
                String hash = response.getAsJsonObject("commit").getAsJsonPrimitive("sha").getAsString();
                dependency.autoGeneratedHash = hash;
                System.out.println("Generated Git Hash for " + dependency.getDisplayName() + ": " + hash);
            } else if (dependency.type == BranchConfig.TYPE.MODRINTH) {
                JsonObject urlOBJ = ConfigLoader.gson.fromJson(dependency.url, JsonObject.class);
                String version = urlOBJ.get("version").getAsString();

                String url = FileHelper.download("https://api.modrinth.com/v2/version/" + version, JsonObject.class).getAsJsonArray("files").get(0).getAsJsonObject().get("url").getAsString();
                urlOBJ.addProperty("url", url);
                dependency.url = urlOBJ.toString();
                dependency.autoGeneratedHash = hash(url);
            } else {
                dependency.autoGeneratedHash = hash(dependency.url);
            }
        }
    }

    private static String hash(String url) {
        try (InputStream in = FileHelper.openFileOrURL(url)) {
            byte[] data = in.readAllBytes();
            String hash = FileHelper.hashFile(data);
            System.out.println("Generated Hash for " + url + ": " + hash);
            return hash;
        } catch (Exception e) {
            e.printStackTrace();
        }

        return null;
    }
}