package net.kyrptonaught.ToolBox.configs;

public class BranchConfig {
    public int config_version = 2;

    public String name;

    public String launchCMD;

    public String game_version;
    public String loader = "Fabric";
    public String java_version;

    public Dependency[] dependencies;

    public static class Dependency {
        public TYPE type;
        public String name;
        public String displayName;
        public String url;
        public String location;
        public String autoGeneratedHash;

        public Boolean optional;
        public Boolean ignore;

        public String getDisplayName() {
            if (displayName == null) return name;
            return displayName;
        }
    }

    public enum TYPE {
        JAR,
        GIT,
        ZIP,
        MODRINTH,
        IGNORE
    }
}